# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- none

pool:
  vmImage: windows-2022

variables:
  - group: maui-android-pipeline

steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: Download keystore 
  inputs:
    secureFile: '$(keyStoreFile)'

- script: |
    mv $(keystore.secureFilePath) $(System.DefaultWorkingDirectory)\NNDIP.Maui
    dir
    echo 'dotnet publish NNDIP.Maui.csproj -f net7.0-android -c Release //p:AndroidSigningStorePass="$(AndroidSigningStorePass)" //p:AndroidSigningKeyPass="$(AndroidSigningKeyPass)" //p:AndroidSigningKeyAlias="$(AndroidSigningKeyAlias)" //p:AndroidSigningKeyAlias="$(keyStoreFile)" //p:AndroidKeyStore="true"'

- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '7.x'
- task: Bash@3
  displayName: Install MAUI
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear 
      dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

- task: Bash@3
  displayName: Restore nuget
  inputs:
    targetType: 'inline'
    script: |
      cd NNDIP.Maui/
      dotnet restore NNDIP.Maui.csproj
# https://docs.microsoft.com/en-us/dotnet/maui/android/deployment/overview

- task: Bash@3
  displayName: Build Android App
  inputs:
    targetType: 'inline'
    script: |
      cd NNDIP.Maui/
      dotnet publish NNDIP.Maui.csproj -f net7.0-android -c Release //p:AndroidSigningStorePass="$(AndroidSigningStorePass)" //p:AndroidSigningKeyPass="$(AndroidSigningKeyPass)" //p:AndroidSigningKeyAlias="$(AndroidSigningKeyAlias)" //p:AndroidSigningKeyAlias="$(keyStoreFile)" //p:AndroidKeyStore="true"
# Signing Android App : https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-android-app

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: |
      '**/*-Signed.aab'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop_android'
    publishLocation: 'Container'

