trigger:
- master

variables:
  - group: maui-ios-pipeline

pool:
  vmImage: macos-latest

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'MyDistributionCertificate.p12'
    certPwd: '$(certificatePassword)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'MyProvisioningProfile.mobileprovision'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: CmdLine@2
  displayName: 'dotnet workload install maui'
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (Release)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'MyMAUIProject.sln'
    arguments: '-f:net6.0-ios -c:Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'