//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNDIP.Maui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNDIP.Maui.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Condition.
        /// </summary>
        public static string dashboardPage_AirCondition {
            get {
                return ResourceManager.GetString("dashboardPage_AirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string dashboardPage_Date {
            get {
                return ResourceManager.GetString("dashboardPage_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device status.
        /// </summary>
        public static string dashboardPage_DeviceStatus {
            get {
                return ResourceManager.GetString("dashboardPage_DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboardPage_PageTitle {
            get {
                return ResourceManager.GetString("dashboardPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperation.
        /// </summary>
        public static string dashboardPage_Recuperation {
            get {
                return ResourceManager.GetString("dashboardPage_Recuperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sensor.
        /// </summary>
        public static string dashboardPage_SelectSensor {
            get {
                return ResourceManager.GetString("dashboardPage_SelectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an unit.
        /// </summary>
        public static string dashboardPage_SelectUnit {
            get {
                return ResourceManager.GetString("dashboardPage_SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor:.
        /// </summary>
        public static string dashboardPage_Sensor {
            get {
                return ResourceManager.GetString("dashboardPage_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor status.
        /// </summary>
        public static string dashboardPage_SensorStatus {
            get {
                return ResourceManager.GetString("dashboardPage_SensorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        public static string dashboardPage_Unit {
            get {
                return ResourceManager.GetString("dashboardPage_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilator.
        /// </summary>
        public static string dashboardPage_Ventilator {
            get {
                return ResourceManager.GetString("dashboardPage_Ventilator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2.
        /// </summary>
        public static string limitPlanPage_Co2 {
            get {
                return ResourceManager.GetString("limitPlanPage_Co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string limitPlanPage_DegreeCelsiusUnit {
            get {
                return ResourceManager.GetString("limitPlanPage_DegreeCelsiusUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        public static string limitPlanPage_Event {
            get {
                return ResourceManager.GetString("limitPlanPage_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High value.
        /// </summary>
        public static string limitPlanPage_HighTemperature {
            get {
                return ResourceManager.GetString("limitPlanPage_HighTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low value.
        /// </summary>
        public static string limitPlanPage_LowTemperature {
            get {
                return ResourceManager.GetString("limitPlanPage_LowTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal value.
        /// </summary>
        public static string limitPlanPage_OptimalCo2 {
            get {
                return ResourceManager.GetString("limitPlanPage_OptimalCo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal value.
        /// </summary>
        public static string limitPlanPage_OptimalTemperature {
            get {
                return ResourceManager.GetString("limitPlanPage_OptimalTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Plan.
        /// </summary>
        public static string limitPlanPage_PageTitle {
            get {
                return ResourceManager.GetString("limitPlanPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string limitPlanPage_PercentageUnit {
            get {
                return ResourceManager.GetString("limitPlanPage_PercentageUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ppm.
        /// </summary>
        public static string limitPlanPage_PpmUnit {
            get {
                return ResourceManager.GetString("limitPlanPage_PpmUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string limitPlanPage_Save {
            get {
                return ResourceManager.GetString("limitPlanPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an event.
        /// </summary>
        public static string limitPlanPage_SelectEvent {
            get {
                return ResourceManager.GetString("limitPlanPage_SelectEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string limitPlanPage_Summer {
            get {
                return ResourceManager.GetString("limitPlanPage_Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string limitPlanPage_Temperature {
            get {
                return ResourceManager.GetString("limitPlanPage_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold value.
        /// </summary>
        public static string limitPlanPage_ThresholdCo2 {
            get {
                return ResourceManager.GetString("limitPlanPage_ThresholdCo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string limitPlanPage_Winter {
            get {
                return ResourceManager.GetString("limitPlanPage_Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string loginPage_LoginToAccount {
            get {
                return ResourceManager.GetString("loginPage_LoginToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginPage_PageTitle {
            get {
                return ResourceManager.GetString("loginPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string loginPage_Password {
            get {
                return ResourceManager.GetString("loginPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string loginPage_SignIn {
            get {
                return ResourceManager.GetString("loginPage_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string loginPage_Username {
            get {
                return ResourceManager.GetString("loginPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string loginPage_Welcome {
            get {
                return ResourceManager.GetString("loginPage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string manualPlanEditPage_Event {
            get {
                return ResourceManager.GetString("manualPlanEditPage_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string manualPlanEditPage_Name {
            get {
                return ResourceManager.GetString("manualPlanEditPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Plan.
        /// </summary>
        public static string manualPlanEditPage_PageTitle {
            get {
                return ResourceManager.GetString("manualPlanEditPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string manualPlanEditPage_Save {
            get {
                return ResourceManager.GetString("manualPlanEditPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an event.
        /// </summary>
        public static string manualPlanEditPage_SelectEvent {
            get {
                return ResourceManager.GetString("manualPlanEditPage_SelectEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string manualPlanPage_Add {
            get {
                return ResourceManager.GetString("manualPlanPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string manualPlanPage_Delete {
            get {
                return ResourceManager.GetString("manualPlanPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string manualPlanPage_Edit {
            get {
                return ResourceManager.GetString("manualPlanPage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Plan.
        /// </summary>
        public static string manualPlanPage_PageTitle {
            get {
                return ResourceManager.GetString("manualPlanPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string manualPlanPage_Save {
            get {
                return ResourceManager.GetString("manualPlanPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        public static string timePlanEditPage_Event {
            get {
                return ResourceManager.GetString("timePlanEditPage_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string timePlanEditPage_From {
            get {
                return ResourceManager.GetString("timePlanEditPage_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string timePlanEditPage_Name {
            get {
                return ResourceManager.GetString("timePlanEditPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Plan.
        /// </summary>
        public static string timePlanEditPage_PageTitle {
            get {
                return ResourceManager.GetString("timePlanEditPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string timePlanEditPage_Save {
            get {
                return ResourceManager.GetString("timePlanEditPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an event.
        /// </summary>
        public static string timePlanEditPage_SelectEvent {
            get {
                return ResourceManager.GetString("timePlanEditPage_SelectEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string timePlanEditPage_To {
            get {
                return ResourceManager.GetString("timePlanEditPage_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string timePlanPage_Add {
            get {
                return ResourceManager.GetString("timePlanPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string timePlanPage_Delete {
            get {
                return ResourceManager.GetString("timePlanPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string timePlanPage_Edit {
            get {
                return ResourceManager.GetString("timePlanPage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Plan.
        /// </summary>
        public static string timePlanPage_PageTitle {
            get {
                return ResourceManager.GetString("timePlanPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string timePlanPage_Save {
            get {
                return ResourceManager.GetString("timePlanPage_Save", resourceCulture);
            }
        }
    }
}
